spring:
  security:
    auto-configure: false
  h2:
    console:
      enabled: true  # H2 ??? ???
      path: /h2-console  # H2 ?? ?? ??

  datasource:
    url: jdbc:h2:mem:testdb  # H2 ??? DB ?? URL
    driver-class-name: org.h2.Driver
    username: sa  # ?? H2 ????
    password:

  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? ???? (create, create-drop, update ??)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true  # ??? ??
    properties:
      hibernate:
        format_sql: true  # SQL ??? ????? ?? ?? ??


  devtools:
    restart:
      enabled: true  # ????? ?? ??? ?? ???
    livereload:
      enabled: true  # LiveReload ??? (????? ?? ?? ??)
